language: node_js
node_js:
  - 20.9
script:
  - eslint 'src/**'
  - pnpm test:coveralls
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - git checkout main
  - corepack enable
  - corepack prepare pnpm@8.3.1 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
  - pnpm install coveralls
